GET https://localhost:8443/JwtTest
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyaWQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTkzNjA4MzQ4LCJleHAiOjE1OTM2MTAxNDh9.OkecxSfzRUaka7lMq3YeX9yESA43Y8Prl2Bxq2ubyQo

{
}