GET https://101.101.218.52:8443/Spring_Travel-1.0-SNAPSHOT/JwtTest
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyaWQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTk2NDMyMzg0LCJleHAiOjE1OTY0MzQxODR9.JPseC7e8oyek9YNPXgxqlUSuWWhyiSr1SAkoaq47y5g

{
}