GET https://localhost:8443/JwtTest
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyaWQiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTk1Njk0NzAyLCJleHAiOjE1OTU2OTY1MDJ9.q3FI5jhcNRAMukbB5jQHGlkiJtF7pZSCmYxMwGaMw04

{
}