POST http://101.101.218.52:8080/Spring_Travel-1.0-SNAPSHOT/register/user
Content-Type: application/json

{
  "id": "userid",
  "email": "useremail@google.com",
  "password": "userpassword",
  "name": "김이박",
  "gender": "M",
  "nickname": "usernickname"
}