POST https://localhost:8443/register/user
Content-Type: application/json

{
  "id": "userid",
  "email": "useremail@google.com",
  "pass": "userpassword",
  "name": "김이박",
  "gender": "M",
  "nickname": "usernickname"
}