CREATE TABLE User(
  sid INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  name VARCHAR(20) NOT NULL,
  id VARCHAR(20) NOT NULL,
  pass VARCHAR(40) NOT NULL,
  gender VARCHAR(1) NOT NULL,
  email VARCHAR(30) NOT NULL
); 

CREATE INDEX idx_id ON User (id);